server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/simon-1024/tensquare-config.git
  rabbitmq:
    host: 192.168.25.130
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh